export type ProjectSummary={id:number;name:string;slug?:string;description:string;media_count:number;annotation_count:number;annotation_seconds?:number;cover_media_id?:number|null;created_at:string};
export type Label={id:number;project_id:number;name:string;color:string};
export type ExtractStatus='pending'|'extracting'|'ready'|'failed'|string;
export type Media={
  id:number;project_id:number;name:string;kind:'video'|'image';width:number;height:number;
  frame_count:number;fps:number;annotation_count?:number;excluded_count?:number;
  source_fps?:number;source_frame_count?:number;extract_fps?:number|null;
  extract_status?:ExtractStatus;duration_sec?:number;frames_dir?:string|null;
  annotation_seconds?:number;annotation_complete?:boolean;
  reused?:boolean;
};
export type Project={id:number;name:string;slug?:string;description:string;created_at:string;updated_at:string;labels:Label[];media:Media[];media_count?:number;annotation_count?:number;annotation_seconds?:number};
export type DefectStat={name:string;color:string;count:number};
export type MaskSizeCluster={label:string;count:number;mean_pixels:number;share:number};
export type HeatmapGrid={width:number;height:number;values:number[][]};
export type ContinueTarget={project_id:number;project_slug:string|null;media_id:number|null;frame:number|null};
export type DashboardStats={
  project_count:number;
  video_count:number;
  image_count:number;
  frames_extracted:number;
  frames_annotated:number;
  coverage:number;
  avg_width:number;
  avg_height:number;
  avg_megapixels:number;
  defects:DefectStat[];
  heatmap:HeatmapGrid;
  heatmaps?:Record<string,HeatmapGrid>;
  continue?:ContinueTarget|null;
  mask_size_clusters:MaskSizeCluster[];
  mask_count:number;
  video_seconds_total:number;
  image_seconds_total:number;
  avg_seconds_per_video:number;
  avg_seconds_per_image:number;
  seconds_total:number;
};
export type FrameLabel={annotation_id:number;id:number;name:string;color:string;source?:string};
export type FrameInfo={frame:number;annotation_count:number;excluded:boolean;labels:FrameLabel[]};
export type Annotation={id:number;media_id:number;frame:number;label_id:number;label_name:string;label_color:string;source:'manual'|'auto'|string;track_group?:string|null};
export type PromptPoint={x:number;y:number;positive:boolean};
export type BoxPrompt=[number,number,number,number];
export type ToolMode='select'|'positive'|'negative'|'box'|'brush'|'erase'|'pan';
export type TrackingJob={id:string;media_id:number;annotation_id?:number|null;annotation_ids?:number[];start_frame:number;end_frame:number;frame_step:number;status:string;progress:number;current_frame?:number|null;created_annotations:number[];removed:number;error?:string|null};
export type ExportFormat='coco'|'yolo'|'voc'|'native';
export type ExportJob={
  id:string;
  fmt:ExportFormat|string;
  project_ids:number[]|null;
  include_unannotated:boolean;
  include_auto:boolean;
  include_manual:boolean;
  status:string;
  progress:number;
  message?:string;
  filename?:string|null;
  error?:string|null;
  image_count?:number;
};
export const mediaReady=(m:Media)=>m.kind==='image'||m.extract_status==='ready'||(!m.extract_status&&m.frame_count>0);
